# Generated by Django 2.1.5 on 2019-11-26 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category_giong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category_loai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category_phukien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('amounts', models.IntegerField()),
                ('cat_giong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Category_giong')),
                ('cat_loai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Category_loai')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('item', models.ManyToManyField(to='SusanPet.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phonenum', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cmmd', models.CharField(blank=True, max_length=30)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province_city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_u', models.IntegerField(default=-1)),
                ('Profile', models.ManyToManyField(blank=True, to='SusanPet.Profile')),
                ('item', models.ManyToManyField(blank=True, to='SusanPet.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Post')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(to='SusanPet.Profile'),
        ),
        migrations.AddField(
            model_name='district',
            name='code_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Province_city'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(blank=True, to='SusanPet.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(blank=True, to='SusanPet.Profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='huyen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.District'),
        ),
        migrations.AddField(
            model_name='address',
            name='tinh',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Province_city'),
        ),
        migrations.AddField(
            model_name='address',
            name='xa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Commune'),
        ),
    ]
