# Generated by Django 2.2.6 on 2019-12-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SusanPet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat_giong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Category_giong'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cat_loai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Category_loai'),
        ),
    ]
