# Generated by Django 2.1.5 on 2019-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SusanPet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='province_city',
            name='id',
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province_city',
            name='code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
