# Generated by Django 2.1.5 on 2019-12-09 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SusanPet', '0003_auto_20191208_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_rs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Profile')),
            ],
        ),
    ]
