# Generated by Django 2.1.5 on 2019-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SusanPet', '0003_auto_20191208_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_giong',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category_loai',
            name='id',
        ),
        migrations.AlterField(
            model_name='category_giong',
            name='name',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category_loai',
            name='name',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
