# Generated by Django 2.1.5 on 2019-12-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SusanPet', '0004_auto_20191208_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_giong',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category_loai',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='cat_giong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Category_giong'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cat_loai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SusanPet.Category_loai'),
        ),
    ]
